"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_sym_db = _symbol_database.Default()
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from ....gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from ....cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from ....axelar.nexus.exported.v1beta1 import types_pb2 as axelar_dot_nexus_dot_exported_dot_v1beta1_dot_types__pb2
from ....axelar.multisig.exported.v1beta1 import types_pb2 as axelar_dot_multisig_dot_exported_dot_v1beta1_dot_types__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eaxelar/evm/v1beta1/types.proto\x12\x12axelar.evm.v1beta1\x1a\x19google/protobuf/any.proto\x1a\x14gogoproto/gogo.proto\x1a\x19cosmos_proto/cosmos.proto\x1a)axelar/nexus/exported/v1beta1/types.proto\x1a,axelar/multisig/exported/v1beta1/types.proto"\x91\x01\n\nVoteEvents\x12R\n\x05chain\x18\x01 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12/\n\x06events\x18\x02 \x03(\x0b2\x19.axelar.evm.v1beta1.EventB\x04\xc8\xde\x1f\x00"\xa4\x07\n\x05Event\x12R\n\x05chain\x18\x01 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12#\n\x05tx_id\x18\x02 \x01(\x0cB\x14\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\xe2\xde\x1f\x04TxID\x12\r\n\x05index\x18\x03 \x01(\x04\x120\n\x06status\x18\x04 \x01(\x0e2 .axelar.evm.v1beta1.Event.Status\x128\n\ntoken_sent\x18\x05 \x01(\x0b2".axelar.evm.v1beta1.EventTokenSentH\x00\x12>\n\rcontract_call\x18\x06 \x01(\x0b2%.axelar.evm.v1beta1.EventContractCallH\x00\x12R\n\x18contract_call_with_token\x18\x07 \x01(\x0b2..axelar.evm.v1beta1.EventContractCallWithTokenH\x00\x125\n\x08transfer\x18\x08 \x01(\x0b2!.axelar.evm.v1beta1.EventTransferH\x00\x12@\n\x0etoken_deployed\x18\t \x01(\x0b2&.axelar.evm.v1beta1.EventTokenDeployedH\x00\x12c\n\x1emultisig_ownership_transferred\x18\n \x01(\x0b25.axelar.evm.v1beta1.EventMultisigOwnershipTransferredB\x02\x18\x01H\x00\x12e\n!multisig_operatorship_transferred\x18\x0b \x01(\x0b28.axelar.evm.v1beta1.EventMultisigOperatorshipTransferredH\x00"\xb8\x01\n\x06Status\x12,\n\x12STATUS_UNSPECIFIED\x10\x00\x1a\x14\x8a\x9d \x10EventNonExistent\x12(\n\x10STATUS_CONFIRMED\x10\x01\x1a\x12\x8a\x9d \x0eEventConfirmed\x12(\n\x10STATUS_COMPLETED\x10\x02\x1a\x12\x8a\x9d \x0eEventCompleted\x12"\n\rSTATUS_FAILED\x10\x03\x1a\x0f\x8a\x9d \x0bEventFailed\x1a\x08\x88\xa3\x1e\x00\xa8\xa4\x1e\x01B\x07\n\x05eventJ\x04\x08\x0c\x10\rJ\x04\x08\r\x10\x0e"\xff\x01\n\x0eEventTokenSent\x12\x1f\n\x06sender\x18\x01 \x01(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12^\n\x11destination_chain\x18\x02 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12\x1b\n\x13destination_address\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12?\n\x06amount\x18\x05 \x01(\x0cB/\xc8\xde\x1f\x00\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint"\xd2\x01\n\x11EventContractCall\x12\x1f\n\x06sender\x18\x01 \x01(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12^\n\x11destination_chain\x18\x02 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12\x18\n\x10contract_address\x18\x03 \x01(\t\x12"\n\x0cpayload_hash\x18\x04 \x01(\x0cB\x0c\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash"\xac\x02\n\x1aEventContractCallWithToken\x12\x1f\n\x06sender\x18\x01 \x01(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12^\n\x11destination_chain\x18\x02 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12\x18\n\x10contract_address\x18\x03 \x01(\t\x12"\n\x0cpayload_hash\x18\x04 \x01(\x0cB\x0c\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\x12\x0e\n\x06symbol\x18\x05 \x01(\t\x12?\n\x06amount\x18\x06 \x01(\x0cB/\xc8\xde\x1f\x00\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint"m\n\rEventTransfer\x12\x1b\n\x02to\x18\x01 \x01(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12?\n\x06amount\x18\x02 \x01(\x0cB/\xc8\xde\x1f\x00\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint"L\n\x12EventTokenDeployed\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12&\n\rtoken_address\x18\x02 \x01(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address"\x82\x02\n!EventMultisigOwnershipTransferred\x12#\n\npre_owners\x18\x01 \x03(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12G\n\x0eprev_threshold\x18\x02 \x01(\x0cB/\xc8\xde\x1f\x00\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\x12#\n\nnew_owners\x18\x03 \x03(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12F\n\rnew_threshold\x18\x04 \x01(\x0cB/\xc8\xde\x1f\x00\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint:\x02\x18\x01"\xe8\x01\n$EventMultisigOperatorshipTransferred\x12&\n\rnew_operators\x18\x03 \x03(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12F\n\rnew_threshold\x18\x04 \x01(\x0cB/\xc8\xde\x1f\x00\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\x12D\n\x0bnew_weights\x18\x05 \x03(\x0cB/\xc8\xde\x1f\x00\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.UintJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03"W\n\x0bNetworkInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12:\n\x02id\x18\x02 \x01(\x0cB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int"\xf8\x01\n\nBurnerInfo\x12\'\n\x0eburner_address\x18\x01 \x01(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12&\n\rtoken_address\x18\x02 \x01(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12^\n\x11destination_chain\x18\x03 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\r\n\x05asset\x18\x05 \x01(\t\x12\x1a\n\x04salt\x18\x06 \x01(\x0cB\x0c\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash"\x9f\x02\n\x0cERC20Deposit\x12#\n\x05tx_id\x18\x01 \x01(\x0cB\x14\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\xe2\xde\x1f\x04TxID\x12?\n\x06amount\x18\x02 \x01(\x0cB/\xc8\xde\x1f\x00\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\x12\r\n\x05asset\x18\x03 \x01(\t\x12^\n\x11destination_chain\x18\x04 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12\'\n\x0eburner_address\x18\x05 \x01(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12\x11\n\tlog_index\x18\x06 \x01(\x04"\xcc\x02\n\x12ERC20TokenMetadata\x12\r\n\x05asset\x18\x01 \x01(\t\x12K\n\x08chain_id\x18\x02 \x01(\x0cB9\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xe2\xde\x1f\x07ChainID\x127\n\x07details\x18\x03 \x01(\x0b2 .axelar.evm.v1beta1.TokenDetailsB\x04\xc8\xde\x1f\x00\x12&\n\rtoken_address\x18\x04 \x01(\tB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07Address\x12\x1d\n\x07tx_hash\x18\x05 \x01(\tB\x0c\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\x12*\n\x06status\x18\x07 \x01(\x0e2\x1a.axelar.evm.v1beta1.Status\x12\x13\n\x0bis_external\x18\x08 \x01(\x08\x12\x13\n\x0bburner_code\x18\t \x01(\x0cJ\x04\x08\x06\x10\x07"A\n\x13TransactionMetadata\x12\x19\n\x06raw_tx\x18\x01 \x01(\x0cB\t\xe2\xde\x1f\x05RawTX\x12\x0f\n\x07pub_key\x18\x02 \x01(\x0c"\xf5\x01\n\x07Command\x12#\n\x02id\x18\x01 \x01(\x0cB\x17\xc8\xde\x1f\x00\xda\xde\x1f\tCommandID\xe2\xde\x1f\x02ID\x12\x13\n\x07command\x18\x02 \x01(\tB\x02\x18\x01\x12\x0e\n\x06params\x18\x03 \x01(\x0c\x12[\n\x06key_id\x18\x04 \x01(\tBK\xe2\xde\x1f\x05KeyID\xfa\xde\x1f>github.com/axelarnetwork/axelar-core/x/multisig/exported.KeyID\x12\x14\n\x0cmax_gas_cost\x18\x05 \x01(\r\x12-\n\x04type\x18\x06 \x01(\x0e2\x1f.axelar.evm.v1beta1.CommandType"\xb8\x03\n\x14CommandBatchMetadata\x12\x12\n\x02id\x18\x01 \x01(\x0cB\x06\xe2\xde\x1f\x02ID\x124\n\x0bcommand_ids\x18\x02 \x03(\x0cB\x1f\xc8\xde\x1f\x00\xda\xde\x1f\tCommandID\xe2\xde\x1f\nCommandIDs\x12\x0c\n\x04data\x18\x03 \x01(\x0c\x12\x1e\n\x08sig_hash\x18\x04 \x01(\x0cB\x0c\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\x129\n\x06status\x18\x05 \x01(\x0e2).axelar.evm.v1beta1.BatchedCommandsStatus\x12[\n\x06key_id\x18\x06 \x01(\tBK\xe2\xde\x1f\x05KeyID\xfa\xde\x1f>github.com/axelarnetwork/axelar-core/x/multisig/exported.KeyID\x12;\n\x18prev_batched_commands_id\x18\x07 \x01(\x0cB\x19\xe2\xde\x1f\x15PrevBatchedCommandsID\x12S\n\tsignature\x18\x08 \x01(\x0b2\x14.google.protobuf.AnyB*\xca\xb4-&github.com/cosmos/codec/ProtoMarshaler"\xba\x01\n\x0bSigMetadata\x12)\n\x04type\x18\x01 \x01(\x0e2\x1b.axelar.evm.v1beta1.SigType\x12R\n\x05chain\x18\x02 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12,\n\x10command_batch_id\x18\x03 \x01(\x0cB\x12\xe2\xde\x1f\x0eCommandBatchID"\x9e\x01\n\x0bTransferKey\x12#\n\x05tx_id\x18\x01 \x01(\x0cB\x14\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\xe2\xde\x1f\x04TxID\x12d\n\x0bnext_key_id\x18\x03 \x01(\tBO\xe2\xde\x1f\tNextKeyID\xfa\xde\x1f>github.com/axelarnetwork/axelar-core/x/multisig/exported.KeyIDJ\x04\x08\x02\x10\x03"i\n\x05Asset\x12R\n\x05chain\x18\x01 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12\x0c\n\x04name\x18\x02 \x01(\t"\x91\x01\n\x0cTokenDetails\x12\x12\n\ntoken_name\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x1b\n\x08decimals\x18\x03 \x01(\rB\t\xfa\xde\x1f\x05uint8\x12@\n\x08capacity\x18\x04 \x01(\x0cB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int"1\n\x07Gateway\x12 \n\x07address\x18\x01 \x01(\x0cB\x0f\xc8\xde\x1f\x00\xda\xde\x1f\x07AddressJ\x04\x08\x02\x10\x03"\x87\x01\n\x0cPollMetadata\x12R\n\x05chain\x18\x01 \x01(\tBC\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName\x12#\n\x05tx_id\x18\x02 \x01(\x0cB\x14\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\xe2\xde\x1f\x04TxID*\xaa\x01\n\x06Status\x12\'\n\x12STATUS_UNSPECIFIED\x10\x00\x1a\x0f\x8a\x9d \x0bNonExistent\x12\'\n\x12STATUS_INITIALIZED\x10\x01\x1a\x0f\x8a\x9d \x0bInitialized\x12\x1f\n\x0eSTATUS_PENDING\x10\x02\x1a\x0b\x8a\x9d \x07Pending\x12#\n\x10STATUS_CONFIRMED\x10\x04\x1a\r\x8a\x9d \tConfirmed\x1a\x08\x88\xa3\x1e\x00\xa8\xa4\x1e\x01*\x90\x02\n\x0bCommandType\x12\x1c\n\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17COMMAND_TYPE_MINT_TOKEN\x10\x01\x12\x1d\n\x19COMMAND_TYPE_DEPLOY_TOKEN\x10\x02\x12\x1b\n\x17COMMAND_TYPE_BURN_TOKEN\x10\x03\x12&\n"COMMAND_TYPE_TRANSFER_OPERATORSHIP\x10\x04\x120\n,COMMAND_TYPE_APPROVE_CONTRACT_CALL_WITH_MINT\x10\x05\x12&\n"COMMAND_TYPE_APPROVE_CONTRACT_CALL\x10\x06\x1a\x08\x88\xa3\x1e\x00\xa8\xa4\x1e\x00*\xff\x01\n\x15BatchedCommandsStatus\x12=\n#BATCHED_COMMANDS_STATUS_UNSPECIFIED\x10\x00\x1a\x14\x8a\x9d \x10BatchNonExistent\x125\n\x1fBATCHED_COMMANDS_STATUS_SIGNING\x10\x01\x1a\x10\x8a\x9d \x0cBatchSigning\x125\n\x1fBATCHED_COMMANDS_STATUS_ABORTED\x10\x02\x1a\x10\x8a\x9d \x0cBatchAborted\x123\n\x1eBATCHED_COMMANDS_STATUS_SIGNED\x10\x03\x1a\x0f\x8a\x9d \x0bBatchSigned\x1a\x04\x88\xa3\x1e\x00*y\n\x07SigType\x12"\n\x14SIG_TYPE_UNSPECIFIED\x10\x00\x1a\x08\x8a\x9d \x04None\x12\x1a\n\x0bSIG_TYPE_TX\x10\x01\x1a\t\x8a\x9d \x05SigTx\x12$\n\x10SIG_TYPE_COMMAND\x10\x02\x1a\x0e\x8a\x9d \nSigCommand\x1a\x08\x88\xa3\x1e\x00\xa8\xa4\x1e\x01*\xc0\x01\n\rDepositStatus\x12(\n\x1aDEPOSIT_STATUS_UNSPECIFIED\x10\x00\x1a\x08\x8a\x9d \x04None\x12\'\n\x16DEPOSIT_STATUS_PENDING\x10\x01\x1a\x0b\x8a\x9d \x07Pending\x12+\n\x18DEPOSIT_STATUS_CONFIRMED\x10\x02\x1a\r\x8a\x9d \tConfirmed\x12%\n\x15DEPOSIT_STATUS_BURNED\x10\x03\x1a\n\x8a\x9d \x06Burned\x1a\x08\x88\xa3\x1e\x01\xa8\xa4\x1e\x01B6Z0github.com/axelarnetwork/axelar-core/x/evm/types\xc8\xe1\x1e\x00b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'axelar.evm.v1beta1.types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'Z0github.com/axelarnetwork/axelar-core/x/evm/types\xc8\xe1\x1e\x00'
    _STATUS._options = None
    _STATUS._serialized_options = b'\x88\xa3\x1e\x00\xa8\xa4\x1e\x01'
    _STATUS.values_by_name['STATUS_UNSPECIFIED']._options = None
    _STATUS.values_by_name['STATUS_UNSPECIFIED']._serialized_options = b'\x8a\x9d \x0bNonExistent'
    _STATUS.values_by_name['STATUS_INITIALIZED']._options = None
    _STATUS.values_by_name['STATUS_INITIALIZED']._serialized_options = b'\x8a\x9d \x0bInitialized'
    _STATUS.values_by_name['STATUS_PENDING']._options = None
    _STATUS.values_by_name['STATUS_PENDING']._serialized_options = b'\x8a\x9d \x07Pending'
    _STATUS.values_by_name['STATUS_CONFIRMED']._options = None
    _STATUS.values_by_name['STATUS_CONFIRMED']._serialized_options = b'\x8a\x9d \tConfirmed'
    _COMMANDTYPE._options = None
    _COMMANDTYPE._serialized_options = b'\x88\xa3\x1e\x00\xa8\xa4\x1e\x00'
    _BATCHEDCOMMANDSSTATUS._options = None
    _BATCHEDCOMMANDSSTATUS._serialized_options = b'\x88\xa3\x1e\x00'
    _BATCHEDCOMMANDSSTATUS.values_by_name['BATCHED_COMMANDS_STATUS_UNSPECIFIED']._options = None
    _BATCHEDCOMMANDSSTATUS.values_by_name['BATCHED_COMMANDS_STATUS_UNSPECIFIED']._serialized_options = b'\x8a\x9d \x10BatchNonExistent'
    _BATCHEDCOMMANDSSTATUS.values_by_name['BATCHED_COMMANDS_STATUS_SIGNING']._options = None
    _BATCHEDCOMMANDSSTATUS.values_by_name['BATCHED_COMMANDS_STATUS_SIGNING']._serialized_options = b'\x8a\x9d \x0cBatchSigning'
    _BATCHEDCOMMANDSSTATUS.values_by_name['BATCHED_COMMANDS_STATUS_ABORTED']._options = None
    _BATCHEDCOMMANDSSTATUS.values_by_name['BATCHED_COMMANDS_STATUS_ABORTED']._serialized_options = b'\x8a\x9d \x0cBatchAborted'
    _BATCHEDCOMMANDSSTATUS.values_by_name['BATCHED_COMMANDS_STATUS_SIGNED']._options = None
    _BATCHEDCOMMANDSSTATUS.values_by_name['BATCHED_COMMANDS_STATUS_SIGNED']._serialized_options = b'\x8a\x9d \x0bBatchSigned'
    _SIGTYPE._options = None
    _SIGTYPE._serialized_options = b'\x88\xa3\x1e\x00\xa8\xa4\x1e\x01'
    _SIGTYPE.values_by_name['SIG_TYPE_UNSPECIFIED']._options = None
    _SIGTYPE.values_by_name['SIG_TYPE_UNSPECIFIED']._serialized_options = b'\x8a\x9d \x04None'
    _SIGTYPE.values_by_name['SIG_TYPE_TX']._options = None
    _SIGTYPE.values_by_name['SIG_TYPE_TX']._serialized_options = b'\x8a\x9d \x05SigTx'
    _SIGTYPE.values_by_name['SIG_TYPE_COMMAND']._options = None
    _SIGTYPE.values_by_name['SIG_TYPE_COMMAND']._serialized_options = b'\x8a\x9d \nSigCommand'
    _DEPOSITSTATUS._options = None
    _DEPOSITSTATUS._serialized_options = b'\x88\xa3\x1e\x01\xa8\xa4\x1e\x01'
    _DEPOSITSTATUS.values_by_name['DEPOSIT_STATUS_UNSPECIFIED']._options = None
    _DEPOSITSTATUS.values_by_name['DEPOSIT_STATUS_UNSPECIFIED']._serialized_options = b'\x8a\x9d \x04None'
    _DEPOSITSTATUS.values_by_name['DEPOSIT_STATUS_PENDING']._options = None
    _DEPOSITSTATUS.values_by_name['DEPOSIT_STATUS_PENDING']._serialized_options = b'\x8a\x9d \x07Pending'
    _DEPOSITSTATUS.values_by_name['DEPOSIT_STATUS_CONFIRMED']._options = None
    _DEPOSITSTATUS.values_by_name['DEPOSIT_STATUS_CONFIRMED']._serialized_options = b'\x8a\x9d \tConfirmed'
    _DEPOSITSTATUS.values_by_name['DEPOSIT_STATUS_BURNED']._options = None
    _DEPOSITSTATUS.values_by_name['DEPOSIT_STATUS_BURNED']._serialized_options = b'\x8a\x9d \x06Burned'
    _VOTEEVENTS.fields_by_name['chain']._options = None
    _VOTEEVENTS.fields_by_name['chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _VOTEEVENTS.fields_by_name['events']._options = None
    _VOTEEVENTS.fields_by_name['events']._serialized_options = b'\xc8\xde\x1f\x00'
    _EVENT_STATUS._options = None
    _EVENT_STATUS._serialized_options = b'\x88\xa3\x1e\x00\xa8\xa4\x1e\x01'
    _EVENT_STATUS.values_by_name['STATUS_UNSPECIFIED']._options = None
    _EVENT_STATUS.values_by_name['STATUS_UNSPECIFIED']._serialized_options = b'\x8a\x9d \x10EventNonExistent'
    _EVENT_STATUS.values_by_name['STATUS_CONFIRMED']._options = None
    _EVENT_STATUS.values_by_name['STATUS_CONFIRMED']._serialized_options = b'\x8a\x9d \x0eEventConfirmed'
    _EVENT_STATUS.values_by_name['STATUS_COMPLETED']._options = None
    _EVENT_STATUS.values_by_name['STATUS_COMPLETED']._serialized_options = b'\x8a\x9d \x0eEventCompleted'
    _EVENT_STATUS.values_by_name['STATUS_FAILED']._options = None
    _EVENT_STATUS.values_by_name['STATUS_FAILED']._serialized_options = b'\x8a\x9d \x0bEventFailed'
    _EVENT.fields_by_name['chain']._options = None
    _EVENT.fields_by_name['chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _EVENT.fields_by_name['tx_id']._options = None
    _EVENT.fields_by_name['tx_id']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\xe2\xde\x1f\x04TxID'
    _EVENT.fields_by_name['multisig_ownership_transferred']._options = None
    _EVENT.fields_by_name['multisig_ownership_transferred']._serialized_options = b'\x18\x01'
    _EVENTTOKENSENT.fields_by_name['sender']._options = None
    _EVENTTOKENSENT.fields_by_name['sender']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _EVENTTOKENSENT.fields_by_name['destination_chain']._options = None
    _EVENTTOKENSENT.fields_by_name['destination_chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _EVENTTOKENSENT.fields_by_name['amount']._options = None
    _EVENTTOKENSENT.fields_by_name['amount']._serialized_options = b"\xc8\xde\x1f\x00\xda\xde\x1f'github.com/cosmos/cosmos-sdk/types.Uint"
    _EVENTCONTRACTCALL.fields_by_name['sender']._options = None
    _EVENTCONTRACTCALL.fields_by_name['sender']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _EVENTCONTRACTCALL.fields_by_name['destination_chain']._options = None
    _EVENTCONTRACTCALL.fields_by_name['destination_chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _EVENTCONTRACTCALL.fields_by_name['payload_hash']._options = None
    _EVENTCONTRACTCALL.fields_by_name['payload_hash']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash'
    _EVENTCONTRACTCALLWITHTOKEN.fields_by_name['sender']._options = None
    _EVENTCONTRACTCALLWITHTOKEN.fields_by_name['sender']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _EVENTCONTRACTCALLWITHTOKEN.fields_by_name['destination_chain']._options = None
    _EVENTCONTRACTCALLWITHTOKEN.fields_by_name['destination_chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _EVENTCONTRACTCALLWITHTOKEN.fields_by_name['payload_hash']._options = None
    _EVENTCONTRACTCALLWITHTOKEN.fields_by_name['payload_hash']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash'
    _EVENTCONTRACTCALLWITHTOKEN.fields_by_name['amount']._options = None
    _EVENTCONTRACTCALLWITHTOKEN.fields_by_name['amount']._serialized_options = b"\xc8\xde\x1f\x00\xda\xde\x1f'github.com/cosmos/cosmos-sdk/types.Uint"
    _EVENTTRANSFER.fields_by_name['to']._options = None
    _EVENTTRANSFER.fields_by_name['to']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _EVENTTRANSFER.fields_by_name['amount']._options = None
    _EVENTTRANSFER.fields_by_name['amount']._serialized_options = b"\xc8\xde\x1f\x00\xda\xde\x1f'github.com/cosmos/cosmos-sdk/types.Uint"
    _EVENTTOKENDEPLOYED.fields_by_name['token_address']._options = None
    _EVENTTOKENDEPLOYED.fields_by_name['token_address']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _EVENTMULTISIGOWNERSHIPTRANSFERRED.fields_by_name['pre_owners']._options = None
    _EVENTMULTISIGOWNERSHIPTRANSFERRED.fields_by_name['pre_owners']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _EVENTMULTISIGOWNERSHIPTRANSFERRED.fields_by_name['prev_threshold']._options = None
    _EVENTMULTISIGOWNERSHIPTRANSFERRED.fields_by_name['prev_threshold']._serialized_options = b"\xc8\xde\x1f\x00\xda\xde\x1f'github.com/cosmos/cosmos-sdk/types.Uint"
    _EVENTMULTISIGOWNERSHIPTRANSFERRED.fields_by_name['new_owners']._options = None
    _EVENTMULTISIGOWNERSHIPTRANSFERRED.fields_by_name['new_owners']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _EVENTMULTISIGOWNERSHIPTRANSFERRED.fields_by_name['new_threshold']._options = None
    _EVENTMULTISIGOWNERSHIPTRANSFERRED.fields_by_name['new_threshold']._serialized_options = b"\xc8\xde\x1f\x00\xda\xde\x1f'github.com/cosmos/cosmos-sdk/types.Uint"
    _EVENTMULTISIGOWNERSHIPTRANSFERRED._options = None
    _EVENTMULTISIGOWNERSHIPTRANSFERRED._serialized_options = b'\x18\x01'
    _EVENTMULTISIGOPERATORSHIPTRANSFERRED.fields_by_name['new_operators']._options = None
    _EVENTMULTISIGOPERATORSHIPTRANSFERRED.fields_by_name['new_operators']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _EVENTMULTISIGOPERATORSHIPTRANSFERRED.fields_by_name['new_threshold']._options = None
    _EVENTMULTISIGOPERATORSHIPTRANSFERRED.fields_by_name['new_threshold']._serialized_options = b"\xc8\xde\x1f\x00\xda\xde\x1f'github.com/cosmos/cosmos-sdk/types.Uint"
    _EVENTMULTISIGOPERATORSHIPTRANSFERRED.fields_by_name['new_weights']._options = None
    _EVENTMULTISIGOPERATORSHIPTRANSFERRED.fields_by_name['new_weights']._serialized_options = b"\xc8\xde\x1f\x00\xda\xde\x1f'github.com/cosmos/cosmos-sdk/types.Uint"
    _NETWORKINFO.fields_by_name['id']._options = None
    _NETWORKINFO.fields_by_name['id']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int'
    _BURNERINFO.fields_by_name['burner_address']._options = None
    _BURNERINFO.fields_by_name['burner_address']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _BURNERINFO.fields_by_name['token_address']._options = None
    _BURNERINFO.fields_by_name['token_address']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _BURNERINFO.fields_by_name['destination_chain']._options = None
    _BURNERINFO.fields_by_name['destination_chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _BURNERINFO.fields_by_name['salt']._options = None
    _BURNERINFO.fields_by_name['salt']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash'
    _ERC20DEPOSIT.fields_by_name['tx_id']._options = None
    _ERC20DEPOSIT.fields_by_name['tx_id']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\xe2\xde\x1f\x04TxID'
    _ERC20DEPOSIT.fields_by_name['amount']._options = None
    _ERC20DEPOSIT.fields_by_name['amount']._serialized_options = b"\xc8\xde\x1f\x00\xda\xde\x1f'github.com/cosmos/cosmos-sdk/types.Uint"
    _ERC20DEPOSIT.fields_by_name['destination_chain']._options = None
    _ERC20DEPOSIT.fields_by_name['destination_chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _ERC20DEPOSIT.fields_by_name['burner_address']._options = None
    _ERC20DEPOSIT.fields_by_name['burner_address']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _ERC20TOKENMETADATA.fields_by_name['chain_id']._options = None
    _ERC20TOKENMETADATA.fields_by_name['chain_id']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xe2\xde\x1f\x07ChainID'
    _ERC20TOKENMETADATA.fields_by_name['details']._options = None
    _ERC20TOKENMETADATA.fields_by_name['details']._serialized_options = b'\xc8\xde\x1f\x00'
    _ERC20TOKENMETADATA.fields_by_name['token_address']._options = None
    _ERC20TOKENMETADATA.fields_by_name['token_address']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _ERC20TOKENMETADATA.fields_by_name['tx_hash']._options = None
    _ERC20TOKENMETADATA.fields_by_name['tx_hash']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash'
    _TRANSACTIONMETADATA.fields_by_name['raw_tx']._options = None
    _TRANSACTIONMETADATA.fields_by_name['raw_tx']._serialized_options = b'\xe2\xde\x1f\x05RawTX'
    _COMMAND.fields_by_name['id']._options = None
    _COMMAND.fields_by_name['id']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\tCommandID\xe2\xde\x1f\x02ID'
    _COMMAND.fields_by_name['command']._options = None
    _COMMAND.fields_by_name['command']._serialized_options = b'\x18\x01'
    _COMMAND.fields_by_name['key_id']._options = None
    _COMMAND.fields_by_name['key_id']._serialized_options = b'\xe2\xde\x1f\x05KeyID\xfa\xde\x1f>github.com/axelarnetwork/axelar-core/x/multisig/exported.KeyID'
    _COMMANDBATCHMETADATA.fields_by_name['id']._options = None
    _COMMANDBATCHMETADATA.fields_by_name['id']._serialized_options = b'\xe2\xde\x1f\x02ID'
    _COMMANDBATCHMETADATA.fields_by_name['command_ids']._options = None
    _COMMANDBATCHMETADATA.fields_by_name['command_ids']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\tCommandID\xe2\xde\x1f\nCommandIDs'
    _COMMANDBATCHMETADATA.fields_by_name['sig_hash']._options = None
    _COMMANDBATCHMETADATA.fields_by_name['sig_hash']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash'
    _COMMANDBATCHMETADATA.fields_by_name['key_id']._options = None
    _COMMANDBATCHMETADATA.fields_by_name['key_id']._serialized_options = b'\xe2\xde\x1f\x05KeyID\xfa\xde\x1f>github.com/axelarnetwork/axelar-core/x/multisig/exported.KeyID'
    _COMMANDBATCHMETADATA.fields_by_name['prev_batched_commands_id']._options = None
    _COMMANDBATCHMETADATA.fields_by_name['prev_batched_commands_id']._serialized_options = b'\xe2\xde\x1f\x15PrevBatchedCommandsID'
    _COMMANDBATCHMETADATA.fields_by_name['signature']._options = None
    _COMMANDBATCHMETADATA.fields_by_name['signature']._serialized_options = b'\xca\xb4-&github.com/cosmos/codec/ProtoMarshaler'
    _SIGMETADATA.fields_by_name['chain']._options = None
    _SIGMETADATA.fields_by_name['chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _SIGMETADATA.fields_by_name['command_batch_id']._options = None
    _SIGMETADATA.fields_by_name['command_batch_id']._serialized_options = b'\xe2\xde\x1f\x0eCommandBatchID'
    _TRANSFERKEY.fields_by_name['tx_id']._options = None
    _TRANSFERKEY.fields_by_name['tx_id']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\xe2\xde\x1f\x04TxID'
    _TRANSFERKEY.fields_by_name['next_key_id']._options = None
    _TRANSFERKEY.fields_by_name['next_key_id']._serialized_options = b'\xe2\xde\x1f\tNextKeyID\xfa\xde\x1f>github.com/axelarnetwork/axelar-core/x/multisig/exported.KeyID'
    _ASSET.fields_by_name['chain']._options = None
    _ASSET.fields_by_name['chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _TOKENDETAILS.fields_by_name['decimals']._options = None
    _TOKENDETAILS.fields_by_name['decimals']._serialized_options = b'\xfa\xde\x1f\x05uint8'
    _TOKENDETAILS.fields_by_name['capacity']._options = None
    _TOKENDETAILS.fields_by_name['capacity']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int'
    _GATEWAY.fields_by_name['address']._options = None
    _GATEWAY.fields_by_name['address']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x07Address'
    _POLLMETADATA.fields_by_name['chain']._options = None
    _POLLMETADATA.fields_by_name['chain']._serialized_options = b'\xfa\xde\x1f?github.com/axelarnetwork/axelar-core/x/nexus/exported.ChainName'
    _POLLMETADATA.fields_by_name['tx_id']._options = None
    _POLLMETADATA.fields_by_name['tx_id']._serialized_options = b'\xc8\xde\x1f\x00\xda\xde\x1f\x04Hash\xe2\xde\x1f\x04TxID'
    _globals['_STATUS']._serialized_start = 5279
    _globals['_STATUS']._serialized_end = 5449
    _globals['_COMMANDTYPE']._serialized_start = 5452
    _globals['_COMMANDTYPE']._serialized_end = 5724
    _globals['_BATCHEDCOMMANDSSTATUS']._serialized_start = 5727
    _globals['_BATCHEDCOMMANDSSTATUS']._serialized_end = 5982
    _globals['_SIGTYPE']._serialized_start = 5984
    _globals['_SIGTYPE']._serialized_end = 6105
    _globals['_DEPOSITSTATUS']._serialized_start = 6108
    _globals['_DEPOSITSTATUS']._serialized_end = 6300
    _globals['_VOTEEVENTS']._serialized_start = 220
    _globals['_VOTEEVENTS']._serialized_end = 365
    _globals['_EVENT']._serialized_start = 368
    _globals['_EVENT']._serialized_end = 1300
    _globals['_EVENT_STATUS']._serialized_start = 1095
    _globals['_EVENT_STATUS']._serialized_end = 1279
    _globals['_EVENTTOKENSENT']._serialized_start = 1303
    _globals['_EVENTTOKENSENT']._serialized_end = 1558
    _globals['_EVENTCONTRACTCALL']._serialized_start = 1561
    _globals['_EVENTCONTRACTCALL']._serialized_end = 1771
    _globals['_EVENTCONTRACTCALLWITHTOKEN']._serialized_start = 1774
    _globals['_EVENTCONTRACTCALLWITHTOKEN']._serialized_end = 2074
    _globals['_EVENTTRANSFER']._serialized_start = 2076
    _globals['_EVENTTRANSFER']._serialized_end = 2185
    _globals['_EVENTTOKENDEPLOYED']._serialized_start = 2187
    _globals['_EVENTTOKENDEPLOYED']._serialized_end = 2263
    _globals['_EVENTMULTISIGOWNERSHIPTRANSFERRED']._serialized_start = 2266
    _globals['_EVENTMULTISIGOWNERSHIPTRANSFERRED']._serialized_end = 2524
    _globals['_EVENTMULTISIGOPERATORSHIPTRANSFERRED']._serialized_start = 2527
    _globals['_EVENTMULTISIGOPERATORSHIPTRANSFERRED']._serialized_end = 2759
    _globals['_NETWORKINFO']._serialized_start = 2761
    _globals['_NETWORKINFO']._serialized_end = 2848
    _globals['_BURNERINFO']._serialized_start = 2851
    _globals['_BURNERINFO']._serialized_end = 3099
    _globals['_ERC20DEPOSIT']._serialized_start = 3102
    _globals['_ERC20DEPOSIT']._serialized_end = 3389
    _globals['_ERC20TOKENMETADATA']._serialized_start = 3392
    _globals['_ERC20TOKENMETADATA']._serialized_end = 3724
    _globals['_TRANSACTIONMETADATA']._serialized_start = 3726
    _globals['_TRANSACTIONMETADATA']._serialized_end = 3791
    _globals['_COMMAND']._serialized_start = 3794
    _globals['_COMMAND']._serialized_end = 4039
    _globals['_COMMANDBATCHMETADATA']._serialized_start = 4042
    _globals['_COMMANDBATCHMETADATA']._serialized_end = 4482
    _globals['_SIGMETADATA']._serialized_start = 4485
    _globals['_SIGMETADATA']._serialized_end = 4671
    _globals['_TRANSFERKEY']._serialized_start = 4674
    _globals['_TRANSFERKEY']._serialized_end = 4832
    _globals['_ASSET']._serialized_start = 4834
    _globals['_ASSET']._serialized_end = 4939
    _globals['_TOKENDETAILS']._serialized_start = 4942
    _globals['_TOKENDETAILS']._serialized_end = 5087
    _globals['_GATEWAY']._serialized_start = 5089
    _globals['_GATEWAY']._serialized_end = 5138
    _globals['_POLLMETADATA']._serialized_start = 5141
    _globals['_POLLMETADATA']._serialized_end = 5276