[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "cosmospy_protobuf"
description = "This package contains a compiled python version of all cosmos protobuf files with their dependencies"
authors = [
    { name = "ctrl-felix", email = "dev@ctrl-felix.de" },
]
readme = "README.md"
keywords = ["cosmospy", "proto", "cosmospy-prtoobuf"]
license = {text = "BSD 3-Clause License"}
classifiers = [
    "Intended Audience  :: Developers",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "protobuf",
]
dynamic = ["version"]

